/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 7TV
 * This is the V3 version of 7TV's API.

This API is in maintenance mode and will not receive any new features.

You can find our terms of service [here](https://7tv.app/legal/terms).

You can find our privacy policy [here](https://7tv.app/legal/privacy).

If you want to report bugs or have any questions, feel free to join our [Discord](https://discord.gg/7tv).

If you want to contribute to the API, feel free to check out our [GitHub](https://github.com/seventv/seventv).

 * OpenAPI spec version: 3.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EmoteSetModel
} from '../../model';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getEmoteSetByIdResponse200 = {
  data: EmoteSetModel
  status: 200
}
    
export type getEmoteSetByIdResponseSuccess = (getEmoteSetByIdResponse200) & {
  headers: Headers;
};
;

export type getEmoteSetByIdResponse = (getEmoteSetByIdResponseSuccess)

export const getGetEmoteSetByIdUrl = (id: string,) => {


  

  return `https://7tv.io/v3/emote-sets/${id}`
}

export const getEmoteSetById = async (id: string, options?: RequestInit): Promise<getEmoteSetByIdResponse> => {
  
  return customFetch<getEmoteSetByIdResponse>(getGetEmoteSetByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetEmoteSetByIdQueryKey = (id?: string,) => {
    return [
    `https://7tv.io/v3/emote-sets/${id}`
    ] as const;
    }

    
export const getGetEmoteSetByIdQueryOptions = <TData = Awaited<ReturnType<typeof getEmoteSetById>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEmoteSetById>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEmoteSetByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEmoteSetById>>> = ({ signal }) => getEmoteSetById(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEmoteSetById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEmoteSetByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getEmoteSetById>>>
export type GetEmoteSetByIdQueryError = unknown


export function useGetEmoteSetById<TData = Awaited<ReturnType<typeof getEmoteSetById>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEmoteSetById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEmoteSetById>>,
          TError,
          Awaited<ReturnType<typeof getEmoteSetById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEmoteSetById<TData = Awaited<ReturnType<typeof getEmoteSetById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEmoteSetById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEmoteSetById>>,
          TError,
          Awaited<ReturnType<typeof getEmoteSetById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEmoteSetById<TData = Awaited<ReturnType<typeof getEmoteSetById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEmoteSetById>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetEmoteSetById<TData = Awaited<ReturnType<typeof getEmoteSetById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEmoteSetById>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEmoteSetByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




