/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 7TV
 * This is the V3 version of 7TV's API.

This API is in maintenance mode and will not receive any new features.

You can find our terms of service [here](https://7tv.app/legal/terms).

You can find our privacy policy [here](https://7tv.app/legal/privacy).

If you want to report bugs or have any questions, feel free to join our [Discord](https://discord.gg/7tv).

If you want to contribute to the API, feel free to check out our [GitHub](https://github.com/seventv/seventv).

 * OpenAPI spec version: 3.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ExtensionConfig
} from '../../model';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getExtensionConfigResponse200 = {
  data: ExtensionConfig
  status: 200
}
    
export type getExtensionConfigResponseSuccess = (getExtensionConfigResponse200) & {
  headers: Headers;
};
;

export type getExtensionConfigResponse = (getExtensionConfigResponseSuccess)

export const getGetExtensionConfigUrl = (name: string,) => {


  

  return `https://7tv.io/v3/config/${name}`
}

export const getExtensionConfig = async (name: string, options?: RequestInit): Promise<getExtensionConfigResponse> => {
  
  return customFetch<getExtensionConfigResponse>(getGetExtensionConfigUrl(name),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetExtensionConfigQueryKey = (name?: string,) => {
    return [
    `https://7tv.io/v3/config/${name}`
    ] as const;
    }

    
export const getGetExtensionConfigQueryOptions = <TData = Awaited<ReturnType<typeof getExtensionConfig>>, TError = unknown>(name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExtensionConfig>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetExtensionConfigQueryKey(name);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getExtensionConfig>>> = ({ signal }) => getExtensionConfig(name, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(name), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getExtensionConfig>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetExtensionConfigQueryResult = NonNullable<Awaited<ReturnType<typeof getExtensionConfig>>>
export type GetExtensionConfigQueryError = unknown


export function useGetExtensionConfig<TData = Awaited<ReturnType<typeof getExtensionConfig>>, TError = unknown>(
 name: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExtensionConfig>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExtensionConfig>>,
          TError,
          Awaited<ReturnType<typeof getExtensionConfig>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExtensionConfig<TData = Awaited<ReturnType<typeof getExtensionConfig>>, TError = unknown>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExtensionConfig>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExtensionConfig>>,
          TError,
          Awaited<ReturnType<typeof getExtensionConfig>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExtensionConfig<TData = Awaited<ReturnType<typeof getExtensionConfig>>, TError = unknown>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExtensionConfig>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetExtensionConfig<TData = Awaited<ReturnType<typeof getExtensionConfig>>, TError = unknown>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExtensionConfig>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetExtensionConfigQueryOptions(name,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




