/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 7TV
 * This is the V3 version of 7TV's API.

This API is in maintenance mode and will not receive any new features.

You can find our terms of service [here](https://7tv.app/legal/terms).

You can find our privacy policy [here](https://7tv.app/legal/privacy).

If you want to report bugs or have any questions, feel free to join our [Discord](https://discord.gg/7tv).

If you want to contribute to the API, feel free to check out our [GitHub](https://github.com/seventv/seventv).

 * OpenAPI spec version: 3.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  XEntitlementData
} from '../../model';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type createEntitlementResponse201 = {
  data: void
  status: 201
}
    
export type createEntitlementResponseSuccess = (createEntitlementResponse201) & {
  headers: Headers;
};
;

export type createEntitlementResponse = (createEntitlementResponseSuccess)

export const getCreateEntitlementUrl = () => {


  

  return `https://7tv.io/v3/entitlements`
}

export const createEntitlement = async (xEntitlementData: XEntitlementData, options?: RequestInit): Promise<createEntitlementResponse> => {
  
  return customFetch<createEntitlementResponse>(getCreateEntitlementUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      xEntitlementData,)
  }
);}




export const getCreateEntitlementMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEntitlement>>, TError,{data: XEntitlementData}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createEntitlement>>, TError,{data: XEntitlementData}, TContext> => {

const mutationKey = ['createEntitlement'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createEntitlement>>, {data: XEntitlementData}> = (props) => {
          const {data} = props ?? {};

          return  createEntitlement(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateEntitlementMutationResult = NonNullable<Awaited<ReturnType<typeof createEntitlement>>>
    export type CreateEntitlementMutationBody = XEntitlementData
    export type CreateEntitlementMutationError = unknown

    export const useCreateEntitlement = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEntitlement>>, TError,{data: XEntitlementData}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createEntitlement>>,
        TError,
        {data: XEntitlementData},
        TContext
      > => {

      const mutationOptions = getCreateEntitlementMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    