/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 7TV
 * This is the V3 version of 7TV's API.

This API is in maintenance mode and will not receive any new features.

You can find our terms of service [here](https://7tv.app/legal/terms).

You can find our privacy policy [here](https://7tv.app/legal/privacy).

If you want to report bugs or have any questions, feel free to join our [Discord](https://discord.gg/7tv).

If you want to contribute to the API, feel free to check out our [GitHub](https://github.com/seventv/seventv).

 * OpenAPI spec version: 3.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChatterinoVersion
} from '../../model';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getVersionInfoResponse200 = {
  data: ChatterinoVersion
  status: 200
}
    
export type getVersionInfoResponseSuccess = (getVersionInfoResponse200) & {
  headers: Headers;
};
;

export type getVersionInfoResponse = (getVersionInfoResponseSuccess)

export const getGetVersionInfoUrl = (os: string,
    branch: string,) => {


  

  return `https://7tv.io/v3/chatterino/version/${os}/${branch}`
}

export const getVersionInfo = async (os: string,
    branch: string, options?: RequestInit): Promise<getVersionInfoResponse> => {
  
  return customFetch<getVersionInfoResponse>(getGetVersionInfoUrl(os,branch),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetVersionInfoQueryKey = (os?: string,
    branch?: string,) => {
    return [
    `https://7tv.io/v3/chatterino/version/${os}/${branch}`
    ] as const;
    }

    
export const getGetVersionInfoQueryOptions = <TData = Awaited<ReturnType<typeof getVersionInfo>>, TError = unknown>(os: string,
    branch: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVersionInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVersionInfoQueryKey(os,branch);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVersionInfo>>> = ({ signal }) => getVersionInfo(os,branch, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(os && branch), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVersionInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetVersionInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getVersionInfo>>>
export type GetVersionInfoQueryError = unknown


export function useGetVersionInfo<TData = Awaited<ReturnType<typeof getVersionInfo>>, TError = unknown>(
 os: string,
    branch: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVersionInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVersionInfo>>,
          TError,
          Awaited<ReturnType<typeof getVersionInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVersionInfo<TData = Awaited<ReturnType<typeof getVersionInfo>>, TError = unknown>(
 os: string,
    branch: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVersionInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVersionInfo>>,
          TError,
          Awaited<ReturnType<typeof getVersionInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVersionInfo<TData = Awaited<ReturnType<typeof getVersionInfo>>, TError = unknown>(
 os: string,
    branch: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVersionInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetVersionInfo<TData = Awaited<ReturnType<typeof getVersionInfo>>, TError = unknown>(
 os: string,
    branch: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVersionInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetVersionInfoQueryOptions(os,branch,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




