/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 7TV
 * This is the V3 version of 7TV's API.

This API is in maintenance mode and will not receive any new features.

You can find our terms of service [here](https://7tv.app/legal/terms).

You can find our privacy policy [here](https://7tv.app/legal/privacy).

If you want to report bugs or have any questions, feel free to join our [Discord](https://discord.gg/7tv).

If you want to contribute to the API, feel free to check out our [GitHub](https://github.com/seventv/seventv).

 * OpenAPI spec version: 3.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EmoteModel
} from '../../model';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type createEmoteResponse201 = {
  data: void
  status: 201
}
    
export type createEmoteResponseSuccess = (createEmoteResponse201) & {
  headers: Headers;
};
;

export type createEmoteResponse = (createEmoteResponseSuccess)

export const getCreateEmoteUrl = () => {


  

  return `https://7tv.io/v3/emotes`
}

export const createEmote = async (createEmoteBody: Blob, options?: RequestInit): Promise<createEmoteResponse> => {
  
  return customFetch<createEmoteResponse>(getCreateEmoteUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'image/*', ...options?.headers },
    body: JSON.stringify(
      createEmoteBody,)
  }
);}




export const getCreateEmoteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEmote>>, TError,{data: Blob}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createEmote>>, TError,{data: Blob}, TContext> => {

const mutationKey = ['createEmote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createEmote>>, {data: Blob}> = (props) => {
          const {data} = props ?? {};

          return  createEmote(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateEmoteMutationResult = NonNullable<Awaited<ReturnType<typeof createEmote>>>
    export type CreateEmoteMutationBody = Blob
    export type CreateEmoteMutationError = unknown

    export const useCreateEmote = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEmote>>, TError,{data: Blob}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createEmote>>,
        TError,
        {data: Blob},
        TContext
      > => {

      const mutationOptions = getCreateEmoteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export type getEmoteByIdResponse200 = {
  data: EmoteModel
  status: 200
}

export type getEmoteByIdResponse404 = {
  data: void
  status: 404
}
    
export type getEmoteByIdResponseSuccess = (getEmoteByIdResponse200) & {
  headers: Headers;
};
export type getEmoteByIdResponseError = (getEmoteByIdResponse404) & {
  headers: Headers;
};

export type getEmoteByIdResponse = (getEmoteByIdResponseSuccess | getEmoteByIdResponseError)

export const getGetEmoteByIdUrl = (id: string,) => {


  

  return `https://7tv.io/v3/emotes/${id}`
}

export const getEmoteById = async (id: string, options?: RequestInit): Promise<getEmoteByIdResponse> => {
  
  return customFetch<getEmoteByIdResponse>(getGetEmoteByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetEmoteByIdQueryKey = (id?: string,) => {
    return [
    `https://7tv.io/v3/emotes/${id}`
    ] as const;
    }

    
export const getGetEmoteByIdQueryOptions = <TData = Awaited<ReturnType<typeof getEmoteById>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEmoteById>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEmoteByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEmoteById>>> = ({ signal }) => getEmoteById(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEmoteById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEmoteByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getEmoteById>>>
export type GetEmoteByIdQueryError = void


export function useGetEmoteById<TData = Awaited<ReturnType<typeof getEmoteById>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEmoteById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEmoteById>>,
          TError,
          Awaited<ReturnType<typeof getEmoteById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEmoteById<TData = Awaited<ReturnType<typeof getEmoteById>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEmoteById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEmoteById>>,
          TError,
          Awaited<ReturnType<typeof getEmoteById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEmoteById<TData = Awaited<ReturnType<typeof getEmoteById>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEmoteById>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetEmoteById<TData = Awaited<ReturnType<typeof getEmoteById>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEmoteById>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEmoteByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




