/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ChannelsRequest
} from '../../model';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Join the specified channels
 */
export type postAdminChannelsResponse200 = {
  data: void
  status: 200
}
    
export type postAdminChannelsResponseSuccess = (postAdminChannelsResponse200) & {
  headers: Headers;
};
;

export type postAdminChannelsResponse = (postAdminChannelsResponseSuccess)

export const getPostAdminChannelsUrl = () => {


  

  return `https://logs.ivr.fi/admin/channels`
}

export const postAdminChannels = async (channelsRequest: ChannelsRequest, options?: RequestInit): Promise<postAdminChannelsResponse> => {
  
  return customFetch<postAdminChannelsResponse>(getPostAdminChannelsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      channelsRequest,)
  }
);}




export const getPostAdminChannelsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminChannels>>, TError,{data: ChannelsRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminChannels>>, TError,{data: ChannelsRequest}, TContext> => {

const mutationKey = ['postAdminChannels'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminChannels>>, {data: ChannelsRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAdminChannels(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminChannelsMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminChannels>>>
    export type PostAdminChannelsMutationBody = ChannelsRequest
    export type PostAdminChannelsMutationError = unknown

    export const usePostAdminChannels = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminChannels>>, TError,{data: ChannelsRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminChannels>>,
        TError,
        {data: ChannelsRequest},
        TContext
      > => {

      const mutationOptions = getPostAdminChannelsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Leave the specified channels
 */
export type deleteAdminChannelsResponse200 = {
  data: void
  status: 200
}
    
export type deleteAdminChannelsResponseSuccess = (deleteAdminChannelsResponse200) & {
  headers: Headers;
};
;

export type deleteAdminChannelsResponse = (deleteAdminChannelsResponseSuccess)

export const getDeleteAdminChannelsUrl = () => {


  

  return `https://logs.ivr.fi/admin/channels`
}

export const deleteAdminChannels = async (channelsRequest: ChannelsRequest, options?: RequestInit): Promise<deleteAdminChannelsResponse> => {
  
  return customFetch<deleteAdminChannelsResponse>(getDeleteAdminChannelsUrl(),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      channelsRequest,)
  }
);}




export const getDeleteAdminChannelsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminChannels>>, TError,{data: ChannelsRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminChannels>>, TError,{data: ChannelsRequest}, TContext> => {

const mutationKey = ['deleteAdminChannels'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminChannels>>, {data: ChannelsRequest}> = (props) => {
          const {data} = props ?? {};

          return  deleteAdminChannels(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminChannelsMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminChannels>>>
    export type DeleteAdminChannelsMutationBody = ChannelsRequest
    export type DeleteAdminChannelsMutationError = unknown

    export const useDeleteAdminChannels = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminChannels>>, TError,{data: ChannelsRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminChannels>>,
        TError,
        {data: ChannelsRequest},
        TContext
      > => {

      const mutationOptions = getDeleteAdminChannelsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    