/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 7TV
 * This is the V3 version of 7TV's API.

This API is in maintenance mode and will not receive any new features.

You can find our terms of service [here](https://7tv.app/legal/terms).

You can find our privacy policy [here](https://7tv.app/legal/privacy).

If you want to report bugs or have any questions, feel free to join our [Discord](https://discord.gg/7tv).

If you want to contribute to the API, feel free to check out our [GitHub](https://github.com/seventv/seventv).

 * OpenAPI spec version: 3.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getDocsResponse200 = {
  data: void
  status: 200
}
    
export type getDocsResponseSuccess = (getDocsResponse200) & {
  headers: Headers;
};
;

export type getDocsResponse = (getDocsResponseSuccess)

export const getGetDocsUrl = () => {


  

  return `https://7tv.io/v3/docs`
}

export const getDocs = async ( options?: RequestInit): Promise<getDocsResponse> => {
  
  return customFetch<getDocsResponse>(getGetDocsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetDocsQueryKey = () => {
    return [
    `https://7tv.io/v3/docs`
    ] as const;
    }

    
export const getGetDocsQueryOptions = <TData = Awaited<ReturnType<typeof getDocs>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocs>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocs>>> = ({ signal }) => getDocs({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDocs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocsQueryResult = NonNullable<Awaited<ReturnType<typeof getDocs>>>
export type GetDocsQueryError = unknown


export function useGetDocs<TData = Awaited<ReturnType<typeof getDocs>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocs>>,
          TError,
          Awaited<ReturnType<typeof getDocs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocs<TData = Awaited<ReturnType<typeof getDocs>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocs>>,
          TError,
          Awaited<ReturnType<typeof getDocs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocs<TData = Awaited<ReturnType<typeof getDocs>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocs>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetDocs<TData = Awaited<ReturnType<typeof getDocs>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocs>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDocsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




