/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 7TV
 * This is the V3 version of 7TV's API.

This API is in maintenance mode and will not receive any new features.

You can find our terms of service [here](https://7tv.app/legal/terms).

You can find our privacy policy [here](https://7tv.app/legal/privacy).

If you want to report bugs or have any questions, feel free to join our [Discord](https://discord.gg/7tv).

If you want to contribute to the API, feel free to check out our [GitHub](https://github.com/seventv/seventv).

 * OpenAPI spec version: 3.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type graphqlHandlerResponseDefault = {
  data: unknown
  status: number
}
    
;
export type graphqlHandlerResponseError = (graphqlHandlerResponseDefault) & {
  headers: Headers;
};

export type graphqlHandlerResponse = (graphqlHandlerResponseError)

export const getGraphqlHandlerUrl = () => {


  

  return `https://7tv.io/v3/gql`
}

export const graphqlHandler = async ( options?: RequestInit): Promise<graphqlHandlerResponse> => {
  
  return customFetch<graphqlHandlerResponse>(getGraphqlHandlerUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getGraphqlHandlerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof graphqlHandler>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof graphqlHandler>>, TError,void, TContext> => {

const mutationKey = ['graphqlHandler'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof graphqlHandler>>, void> = () => {
          

          return  graphqlHandler(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GraphqlHandlerMutationResult = NonNullable<Awaited<ReturnType<typeof graphqlHandler>>>
    
    export type GraphqlHandlerMutationError = unknown

    export const useGraphqlHandler = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof graphqlHandler>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof graphqlHandler>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getGraphqlHandlerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export type playgroundResponseDefault = {
  data: unknown
  status: number
}
    
;
export type playgroundResponseError = (playgroundResponseDefault) & {
  headers: Headers;
};

export type playgroundResponse = (playgroundResponseError)

export const getPlaygroundUrl = () => {


  

  return `https://7tv.io/v3/gql/playground`
}

export const playground = async ( options?: RequestInit): Promise<playgroundResponse> => {
  
  return customFetch<playgroundResponse>(getPlaygroundUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getPlaygroundQueryKey = () => {
    return [
    `https://7tv.io/v3/gql/playground`
    ] as const;
    }

    
export const getPlaygroundQueryOptions = <TData = Awaited<ReturnType<typeof playground>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof playground>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPlaygroundQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof playground>>> = ({ signal }) => playground({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof playground>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PlaygroundQueryResult = NonNullable<Awaited<ReturnType<typeof playground>>>
export type PlaygroundQueryError = unknown


export function usePlayground<TData = Awaited<ReturnType<typeof playground>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof playground>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof playground>>,
          TError,
          Awaited<ReturnType<typeof playground>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePlayground<TData = Awaited<ReturnType<typeof playground>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof playground>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof playground>>,
          TError,
          Awaited<ReturnType<typeof playground>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePlayground<TData = Awaited<ReturnType<typeof playground>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof playground>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePlayground<TData = Awaited<ReturnType<typeof playground>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof playground>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPlaygroundQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




