/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 7TV
 * This is the V3 version of 7TV's API.

This API is in maintenance mode and will not receive any new features.

You can find our terms of service [here](https://7tv.app/legal/terms).

You can find our privacy policy [here](https://7tv.app/legal/privacy).

If you want to report bugs or have any questions, feel free to join our [Discord](https://discord.gg/7tv).

If you want to contribute to the API, feel free to check out our [GitHub](https://github.com/seventv/seventv).

 * OpenAPI spec version: 3.0.0
 */
import type { EmoteSetId } from './emoteSetId';

/**
 * @nullable
 */
export type ActiveEmoteModelOriginId = EmoteSetId | null;
