/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 */
import type { AvailableLogsParamsAllOfFourOneOf } from './availableLogsParamsAllOfFourOneOf';
import type { AvailableLogsParamsAllOfFourOneOfTwo } from './availableLogsParamsAllOfFourOneOfTwo';

export type AvailableLogsParamsAllOfFour = AvailableLogsParamsAllOfFourOneOf | AvailableLogsParamsAllOfFourOneOfTwo;
