/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 */
import type { AvailableLogsParamsAllOfOneOf } from './availableLogsParamsAllOfOneOf';
import type { AvailableLogsParamsAllOfOneOfTwo } from './availableLogsParamsAllOfOneOfTwo';

export type AvailableLogsParamsAllOf = AvailableLogsParamsAllOfOneOf | AvailableLogsParamsAllOfOneOfTwo;
