/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 */
import type { AvailableLogsParamsAllOf } from './availableLogsParamsAllOf';
import type { AvailableLogsParamsAllOfFour } from './availableLogsParamsAllOfFour';

export type AvailableLogsParams = AvailableLogsParamsAllOf & AvailableLogsParamsAllOfFour;
