/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 */

export type ChannelIdType = typeof ChannelIdType[keyof typeof ChannelIdType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChannelIdType = {
  channel: 'channel',
  channelid: 'channelid',
} as const;
