/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 */
import type { ChannelIdType } from './channelIdType';

export interface ChannelLogsByDatePath {
  channel_id_type: ChannelIdType;
  channel: string;
  year: string;
  month: string;
  day: string;
}
