/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 */
import type { UserLogsStats } from './userLogsStats';

export interface ChannelLogsStats {
  /** @minimum 0 */
  messageCount: number;
  topChatters: UserLogsStats[];
}
