/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 7TV
 * This is the V3 version of 7TV's API.

This API is in maintenance mode and will not receive any new features.

You can find our terms of service [here](https://7tv.app/legal/terms).

You can find our privacy policy [here](https://7tv.app/legal/privacy).

If you want to report bugs or have any questions, feel free to join our [Discord](https://discord.gg/7tv).

If you want to contribute to the API, feel free to check out our [GitHub](https://github.com/seventv/seventv).

 * OpenAPI spec version: 3.0.0
 */

/**
 * EmoteLifecycleModel represents the lifecycle of an emote.
- `Deleted` (-1): The emote has been deleted.
- `Pending` (0): The emote is pending approval.
- `Processing` (1): The emote is being processed.
- `Disabled` (2): The emote has been disabled.
- `Live` (3): The emote is live.
- `Failed` (-2): The emote has failed processing.
 */
export type EmoteLifecycleModel = typeof EmoteLifecycleModel[keyof typeof EmoteLifecycleModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EmoteLifecycleModel = {
  NUMBER_MINUS_1: -1,
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_MINUS_2: -2,
} as const;
