/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 */

export type GetChannelIdTypeChannelRandomParams = {
json?: boolean;
jsonBasic?: boolean;
raw?: boolean;
reverse?: boolean;
ndjson?: boolean;
/**
 * @minimum 0
 */
limit?: number | null;
/**
 * @minimum 0
 */
offset?: number | null;
};
