/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 */

export type GetChannelIdTypeChannelStatsParams = {
/**
 * RFC 3339 start date
 */
from?: string | null;
/**
 * RFC 3339 end date
 */
to?: string | null;
};
