/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 */
import type { FullMessage } from './fullMessage';

/**
 * Used for schema only, actual serialization is manual
 */
export interface JsonLogsResponse {
  messages: FullMessage[];
}
