/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 */
import type { LogRangeParamsFrom } from './logRangeParamsFrom';
import type { LogRangeParamsTo } from './logRangeParamsTo';

export interface LogRangeParams {
  /** RFC 3339 start date */
  from?: LogRangeParamsFrom;
  /** RFC 3339 end date */
  to?: LogRangeParamsTo;
}
