/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 */
import type { LogsParamsLimit } from './logsParamsLimit';
import type { LogsParamsOffset } from './logsParamsOffset';

export interface LogsParams {
  json?: boolean;
  jsonBasic?: boolean;
  raw?: boolean;
  reverse?: boolean;
  ndjson?: boolean;
  /** @minimum 0 */
  limit?: LogsParamsLimit;
  /** @minimum 0 */
  offset?: LogsParamsOffset;
}
