/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 */
import type { ChannelIdType } from './channelIdType';

export interface LogsPathChannel {
  channel_id_type: ChannelIdType;
  channel: string;
}
