/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 7TV
 * This is the V3 version of 7TV's API.

This API is in maintenance mode and will not receive any new features.

You can find our terms of service [here](https://7tv.app/legal/terms).

You can find our privacy policy [here](https://7tv.app/legal/privacy).

If you want to report bugs or have any questions, feel free to join our [Discord](https://discord.gg/7tv).

If you want to contribute to the API, feel free to check out our [GitHub](https://github.com/seventv/seventv).

 * OpenAPI spec version: 3.0.0
 */

/**
 * These flags are used to define what permissions a user editor has.

- `ModifyEmotes` (1): Allows modifying emotes in the user's active emote sets

- `UsePrivateEmotes` (2): Allows using the user's private emotes

- `ManageProfile` (4): Allows managing the user's public profile

- `ManageOwnedEmotes` (8): Allows managing the user's owned emotes

- `ManageEmoteSets` (16): Allows managing the user's owned emote sets

- `ManageBilling` (32): Allows managing billing and payments, such as subscriptions

- `ManageEditors` (64): Allows adding or removing editors for the user

- `ViewMessages` (128): Allows viewing the user's private messages, such as inbox
 */
export type UserEditorModelPermission = number;
