/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 7TV
 * This is the V3 version of 7TV's API.

This API is in maintenance mode and will not receive any new features.

You can find our terms of service [here](https://7tv.app/legal/terms).

You can find our privacy policy [here](https://7tv.app/legal/privacy).

If you want to report bugs or have any questions, feel free to join our [Discord](https://discord.gg/7tv).

If you want to contribute to the API, feel free to check out our [GitHub](https://github.com/seventv/seventv).

 * OpenAPI spec version: 3.0.0
 */
import type { UserConnectionModel } from './userConnectionModel';
import type { UserEditorModel } from './userEditorModel';
import type { EmoteSetPartialModel } from './emoteSetPartialModel';
import type { UserId } from './userId';
import type { RoleId } from './roleId';
import type { UserStyle } from './userStyle';
import type { UserTypeModel } from './userTypeModel';

export interface UserModel {
  avatar_url?: string;
  biography?: string;
  connections?: UserConnectionModel[];
  /** @minimum 0 */
  created_at?: number;
  display_name?: string;
  editors?: UserEditorModel[];
  emote_sets?: EmoteSetPartialModel[];
  id?: UserId;
  roles?: RoleId[];
  style?: UserStyle;
  user_type?: UserTypeModel;
  username?: string;
}
