/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 */
import type { UserLogsStatsUserLogin } from './userLogsStatsUserLogin';

export interface UserLogsStats {
  userId: string;
  userLogin?: UserLogsStatsUserLogin;
  /** @minimum 0 */
  messageCount: number;
}
