/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 */
import type { ChannelIdType } from './channelIdType';
import type { UserIdType } from './userIdType';

export interface UserLogPathParams {
  channel_id_type: ChannelIdType;
  channel: string;
  user_id_type: UserIdType;
  user: string;
}
