/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 */

export type UserIdType = typeof UserIdType[keyof typeof UserIdType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserIdType = {
  user: 'user',
  userid: 'userid',
} as const;
