/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChannelChannelRouteImport } from './routes/channel/$channel'
import { Route as UserChannelUserRouteImport } from './routes/user/$channel.$user'
import { Route as ChannelChannelStatsRouteImport } from './routes/channel/$channel.stats'
import { Route as UserChannelUserStatsRouteImport } from './routes/user/$channel.$user.stats'
import { Route as UserChannelUserSearchRouteImport } from './routes/user/$channel.$user.search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelRoute = ChannelChannelRouteImport.update({
  id: '/channel/$channel',
  path: '/channel/$channel',
  getParentRoute: () => rootRouteImport,
} as any)
const UserChannelUserRoute = UserChannelUserRouteImport.update({
  id: '/user/$channel/$user',
  path: '/user/$channel/$user',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelStatsRoute = ChannelChannelStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => ChannelChannelRoute,
} as any)
const UserChannelUserStatsRoute = UserChannelUserStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => UserChannelUserRoute,
} as any)
const UserChannelUserSearchRoute = UserChannelUserSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => UserChannelUserRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channel/$channel': typeof ChannelChannelRouteWithChildren
  '/channel/$channel/stats': typeof ChannelChannelStatsRoute
  '/user/$channel/$user': typeof UserChannelUserRouteWithChildren
  '/user/$channel/$user/search': typeof UserChannelUserSearchRoute
  '/user/$channel/$user/stats': typeof UserChannelUserStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channel/$channel': typeof ChannelChannelRouteWithChildren
  '/channel/$channel/stats': typeof ChannelChannelStatsRoute
  '/user/$channel/$user': typeof UserChannelUserRouteWithChildren
  '/user/$channel/$user/search': typeof UserChannelUserSearchRoute
  '/user/$channel/$user/stats': typeof UserChannelUserStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channel/$channel': typeof ChannelChannelRouteWithChildren
  '/channel/$channel/stats': typeof ChannelChannelStatsRoute
  '/user/$channel/$user': typeof UserChannelUserRouteWithChildren
  '/user/$channel/$user/search': typeof UserChannelUserSearchRoute
  '/user/$channel/$user/stats': typeof UserChannelUserStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channel/$channel'
    | '/channel/$channel/stats'
    | '/user/$channel/$user'
    | '/user/$channel/$user/search'
    | '/user/$channel/$user/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channel/$channel'
    | '/channel/$channel/stats'
    | '/user/$channel/$user'
    | '/user/$channel/$user/search'
    | '/user/$channel/$user/stats'
  id:
    | '__root__'
    | '/'
    | '/channel/$channel'
    | '/channel/$channel/stats'
    | '/user/$channel/$user'
    | '/user/$channel/$user/search'
    | '/user/$channel/$user/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelChannelRoute: typeof ChannelChannelRouteWithChildren
  UserChannelUserRoute: typeof UserChannelUserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channel': {
      id: '/channel/$channel'
      path: '/channel/$channel'
      fullPath: '/channel/$channel'
      preLoaderRoute: typeof ChannelChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$channel/$user': {
      id: '/user/$channel/$user'
      path: '/user/$channel/$user'
      fullPath: '/user/$channel/$user'
      preLoaderRoute: typeof UserChannelUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channel/stats': {
      id: '/channel/$channel/stats'
      path: '/stats'
      fullPath: '/channel/$channel/stats'
      preLoaderRoute: typeof ChannelChannelStatsRouteImport
      parentRoute: typeof ChannelChannelRoute
    }
    '/user/$channel/$user/stats': {
      id: '/user/$channel/$user/stats'
      path: '/stats'
      fullPath: '/user/$channel/$user/stats'
      preLoaderRoute: typeof UserChannelUserStatsRouteImport
      parentRoute: typeof UserChannelUserRoute
    }
    '/user/$channel/$user/search': {
      id: '/user/$channel/$user/search'
      path: '/search'
      fullPath: '/user/$channel/$user/search'
      preLoaderRoute: typeof UserChannelUserSearchRouteImport
      parentRoute: typeof UserChannelUserRoute
    }
  }
}

interface ChannelChannelRouteChildren {
  ChannelChannelStatsRoute: typeof ChannelChannelStatsRoute
}

const ChannelChannelRouteChildren: ChannelChannelRouteChildren = {
  ChannelChannelStatsRoute: ChannelChannelStatsRoute,
}

const ChannelChannelRouteWithChildren = ChannelChannelRoute._addFileChildren(
  ChannelChannelRouteChildren,
)

interface UserChannelUserRouteChildren {
  UserChannelUserSearchRoute: typeof UserChannelUserSearchRoute
  UserChannelUserStatsRoute: typeof UserChannelUserStatsRoute
}

const UserChannelUserRouteChildren: UserChannelUserRouteChildren = {
  UserChannelUserSearchRoute: UserChannelUserSearchRoute,
  UserChannelUserStatsRoute: UserChannelUserStatsRoute,
}

const UserChannelUserRouteWithChildren = UserChannelUserRoute._addFileChildren(
  UserChannelUserRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelChannelRoute: ChannelChannelRouteWithChildren,
  UserChannelUserRoute: UserChannelUserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
