/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChannelChannelIndexRouteImport } from './routes/channel/$channel/index'
import { Route as ChannelChannelStatsRouteImport } from './routes/channel/$channel/stats'
import { Route as UserChannelUserIndexRouteImport } from './routes/user/$channel.$user/index'
import { Route as UserChannelUserStatsRouteImport } from './routes/user/$channel.$user/stats'
import { Route as UserChannelUserSearchRouteImport } from './routes/user/$channel.$user/search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIndexRoute = ChannelChannelIndexRouteImport.update({
  id: '/channel/$channel/',
  path: '/channel/$channel/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelStatsRoute = ChannelChannelStatsRouteImport.update({
  id: '/channel/$channel/stats',
  path: '/channel/$channel/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const UserChannelUserIndexRoute = UserChannelUserIndexRouteImport.update({
  id: '/user/$channel/$user/',
  path: '/user/$channel/$user/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserChannelUserStatsRoute = UserChannelUserStatsRouteImport.update({
  id: '/user/$channel/$user/stats',
  path: '/user/$channel/$user/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const UserChannelUserSearchRoute = UserChannelUserSearchRouteImport.update({
  id: '/user/$channel/$user/search',
  path: '/user/$channel/$user/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channel/$channel/stats': typeof ChannelChannelStatsRoute
  '/channel/$channel': typeof ChannelChannelIndexRoute
  '/user/$channel/$user/search': typeof UserChannelUserSearchRoute
  '/user/$channel/$user/stats': typeof UserChannelUserStatsRoute
  '/user/$channel/$user': typeof UserChannelUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channel/$channel/stats': typeof ChannelChannelStatsRoute
  '/channel/$channel': typeof ChannelChannelIndexRoute
  '/user/$channel/$user/search': typeof UserChannelUserSearchRoute
  '/user/$channel/$user/stats': typeof UserChannelUserStatsRoute
  '/user/$channel/$user': typeof UserChannelUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channel/$channel/stats': typeof ChannelChannelStatsRoute
  '/channel/$channel/': typeof ChannelChannelIndexRoute
  '/user/$channel/$user/search': typeof UserChannelUserSearchRoute
  '/user/$channel/$user/stats': typeof UserChannelUserStatsRoute
  '/user/$channel/$user/': typeof UserChannelUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channel/$channel/stats'
    | '/channel/$channel'
    | '/user/$channel/$user/search'
    | '/user/$channel/$user/stats'
    | '/user/$channel/$user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channel/$channel/stats'
    | '/channel/$channel'
    | '/user/$channel/$user/search'
    | '/user/$channel/$user/stats'
    | '/user/$channel/$user'
  id:
    | '__root__'
    | '/'
    | '/channel/$channel/stats'
    | '/channel/$channel/'
    | '/user/$channel/$user/search'
    | '/user/$channel/$user/stats'
    | '/user/$channel/$user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelChannelStatsRoute: typeof ChannelChannelStatsRoute
  ChannelChannelIndexRoute: typeof ChannelChannelIndexRoute
  UserChannelUserSearchRoute: typeof UserChannelUserSearchRoute
  UserChannelUserStatsRoute: typeof UserChannelUserStatsRoute
  UserChannelUserIndexRoute: typeof UserChannelUserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channel/': {
      id: '/channel/$channel/'
      path: '/channel/$channel'
      fullPath: '/channel/$channel'
      preLoaderRoute: typeof ChannelChannelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channel/stats': {
      id: '/channel/$channel/stats'
      path: '/channel/$channel/stats'
      fullPath: '/channel/$channel/stats'
      preLoaderRoute: typeof ChannelChannelStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$channel/$user/': {
      id: '/user/$channel/$user/'
      path: '/user/$channel/$user'
      fullPath: '/user/$channel/$user'
      preLoaderRoute: typeof UserChannelUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$channel/$user/stats': {
      id: '/user/$channel/$user/stats'
      path: '/user/$channel/$user/stats'
      fullPath: '/user/$channel/$user/stats'
      preLoaderRoute: typeof UserChannelUserStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$channel/$user/search': {
      id: '/user/$channel/$user/search'
      path: '/user/$channel/$user/search'
      fullPath: '/user/$channel/$user/search'
      preLoaderRoute: typeof UserChannelUserSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelChannelStatsRoute: ChannelChannelStatsRoute,
  ChannelChannelIndexRoute: ChannelChannelIndexRoute,
  UserChannelUserSearchRoute: UserChannelUserSearchRoute,
  UserChannelUserStatsRoute: UserChannelUserStatsRoute,
  UserChannelUserIndexRoute: UserChannelUserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
