/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 7TV
 * This is the V3 version of 7TV's API.

This API is in maintenance mode and will not receive any new features.

You can find our terms of service [here](https://7tv.app/legal/terms).

You can find our privacy policy [here](https://7tv.app/legal/privacy).

If you want to report bugs or have any questions, feel free to join our [Discord](https://discord.gg/7tv).

If you want to contribute to the API, feel free to check out our [GitHub](https://github.com/seventv/seventv).

 * OpenAPI spec version: 3.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiError,
  PresenceModel,
  UserConnectionModel,
  UserModel
} from '../../model';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getUserByIdResponse200 = {
  data: UserModel
  status: 200
}
    
export type getUserByIdResponseSuccess = (getUserByIdResponse200) & {
  headers: Headers;
};
;

export type getUserByIdResponse = (getUserByIdResponseSuccess)

export const getGetUserByIdUrl = (id: string,) => {


  

  return `https://7tv.io/v3/users/${id}`
}

export const getUserById = async (id: string, options?: RequestInit): Promise<getUserByIdResponse> => {
  
  return customFetch<getUserByIdResponse>(getGetUserByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUserByIdQueryKey = (id?: string,) => {
    return [
    `https://7tv.io/v3/users/${id}`
    ] as const;
    }

    
export const getGetUserByIdQueryOptions = <TData = Awaited<ReturnType<typeof getUserById>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserById>>> = ({ signal }) => getUserById(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getUserById>>>
export type GetUserByIdQueryError = unknown


export function useGetUserById<TData = Awaited<ReturnType<typeof getUserById>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserById>>,
          TError,
          Awaited<ReturnType<typeof getUserById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserById<TData = Awaited<ReturnType<typeof getUserById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserById>>,
          TError,
          Awaited<ReturnType<typeof getUserById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserById<TData = Awaited<ReturnType<typeof getUserById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserById<TData = Awaited<ReturnType<typeof getUserById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export type deleteUserByIdResponse204 = {
  data: void
  status: 204
}

export type deleteUserByIdResponse404 = {
  data: ApiError
  status: 404
}
    
export type deleteUserByIdResponseSuccess = (deleteUserByIdResponse204) & {
  headers: Headers;
};
export type deleteUserByIdResponseError = (deleteUserByIdResponse404) & {
  headers: Headers;
};

export type deleteUserByIdResponse = (deleteUserByIdResponseSuccess | deleteUserByIdResponseError)

export const getDeleteUserByIdUrl = (id: string,) => {


  

  return `https://7tv.io/v3/users/${id}`
}

export const deleteUserById = async (id: string, options?: RequestInit): Promise<deleteUserByIdResponse> => {
  
  return customFetch<deleteUserByIdResponse>(getDeleteUserByIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteUserByIdMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUserById>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteUserById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUserById>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteUserById(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUserById>>>
    
    export type DeleteUserByIdMutationError = ApiError

    export const useDeleteUserById = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUserById>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteUserByIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export type updateUserConnectionByIdResponse200 = {
  data: UserConnectionModel
  status: 200
}

export type updateUserConnectionByIdResponse404 = {
  data: ApiError
  status: 404
}
    
export type updateUserConnectionByIdResponseSuccess = (updateUserConnectionByIdResponse200) & {
  headers: Headers;
};
export type updateUserConnectionByIdResponseError = (updateUserConnectionByIdResponse404) & {
  headers: Headers;
};

export type updateUserConnectionByIdResponse = (updateUserConnectionByIdResponseSuccess | updateUserConnectionByIdResponseError)

export const getUpdateUserConnectionByIdUrl = (id: string,
    connectionId: string,) => {


  

  return `https://7tv.io/v3/users/${id}/connections/${connectionId}`
}

export const updateUserConnectionById = async (id: string,
    connectionId: string, options?: RequestInit): Promise<updateUserConnectionByIdResponse> => {
  
  return customFetch<updateUserConnectionByIdResponse>(getUpdateUserConnectionByIdUrl(id,connectionId),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
);}




export const getUpdateUserConnectionByIdMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserConnectionById>>, TError,{id: string;connectionId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUserConnectionById>>, TError,{id: string;connectionId: string}, TContext> => {

const mutationKey = ['updateUserConnectionById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUserConnectionById>>, {id: string;connectionId: string}> = (props) => {
          const {id,connectionId} = props ?? {};

          return  updateUserConnectionById(id,connectionId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserConnectionByIdMutationResult = NonNullable<Awaited<ReturnType<typeof updateUserConnectionById>>>
    
    export type UpdateUserConnectionByIdMutationError = ApiError

    export const useUpdateUserConnectionById = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserConnectionById>>, TError,{id: string;connectionId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUserConnectionById>>,
        TError,
        {id: string;connectionId: string},
        TContext
      > => {

      const mutationOptions = getUpdateUserConnectionByIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export type createUserPresenceResponse200 = {
  data: PresenceModel
  status: 200
}
    
export type createUserPresenceResponseSuccess = (createUserPresenceResponse200) & {
  headers: Headers;
};
;

export type createUserPresenceResponse = (createUserPresenceResponseSuccess)

export const getCreateUserPresenceUrl = (id: string,) => {


  

  return `https://7tv.io/v3/users/${id}/presences`
}

export const createUserPresence = async (id: string, options?: RequestInit): Promise<createUserPresenceResponse> => {
  
  return customFetch<createUserPresenceResponse>(getCreateUserPresenceUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getCreateUserPresenceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUserPresence>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createUserPresence>>, TError,{id: string}, TContext> => {

const mutationKey = ['createUserPresence'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUserPresence>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  createUserPresence(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateUserPresenceMutationResult = NonNullable<Awaited<ReturnType<typeof createUserPresence>>>
    
    export type CreateUserPresenceMutationError = unknown

    export const useCreateUserPresence = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUserPresence>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUserPresence>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getCreateUserPresenceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export type uploadUserProfilePictureResponse200 = {
  data: void
  status: 200
}
    
export type uploadUserProfilePictureResponseSuccess = (uploadUserProfilePictureResponse200) & {
  headers: Headers;
};
;

export type uploadUserProfilePictureResponse = (uploadUserProfilePictureResponseSuccess)

export const getUploadUserProfilePictureUrl = (id: string,) => {


  

  return `https://7tv.io/v3/users/${id}/profile-picture`
}

export const uploadUserProfilePicture = async (id: string,
    uploadUserProfilePictureBody: Blob, options?: RequestInit): Promise<uploadUserProfilePictureResponse> => {
  
  return customFetch<uploadUserProfilePictureResponse>(getUploadUserProfilePictureUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'image/*', ...options?.headers },
    body: JSON.stringify(
      uploadUserProfilePictureBody,)
  }
);}




export const getUploadUserProfilePictureMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadUserProfilePicture>>, TError,{id: string;data: Blob}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadUserProfilePicture>>, TError,{id: string;data: Blob}, TContext> => {

const mutationKey = ['uploadUserProfilePicture'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadUserProfilePicture>>, {id: string;data: Blob}> = (props) => {
          const {id,data} = props ?? {};

          return  uploadUserProfilePicture(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadUserProfilePictureMutationResult = NonNullable<Awaited<ReturnType<typeof uploadUserProfilePicture>>>
    export type UploadUserProfilePictureMutationBody = Blob
    export type UploadUserProfilePictureMutationError = unknown

    export const useUploadUserProfilePicture = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadUserProfilePicture>>, TError,{id: string;data: Blob}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadUserProfilePicture>>,
        TError,
        {id: string;data: Blob},
        TContext
      > => {

      const mutationOptions = getUploadUserProfilePictureMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export type getUserByPlatformIdResponse200 = {
  data: UserModel
  status: 200
}

export type getUserByPlatformIdResponse404 = {
  data: ApiError
  status: 404
}
    
export type getUserByPlatformIdResponseSuccess = (getUserByPlatformIdResponse200) & {
  headers: Headers;
};
export type getUserByPlatformIdResponseError = (getUserByPlatformIdResponse404) & {
  headers: Headers;
};

export type getUserByPlatformIdResponse = (getUserByPlatformIdResponseSuccess | getUserByPlatformIdResponseError)

export const getGetUserByPlatformIdUrl = (platform: string,
    platformId: string,) => {


  

  return `https://7tv.io/v3/users/${platform}/${platformId}`
}

export const getUserByPlatformId = async (platform: string,
    platformId: string, options?: RequestInit): Promise<getUserByPlatformIdResponse> => {
  
  return customFetch<getUserByPlatformIdResponse>(getGetUserByPlatformIdUrl(platform,platformId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUserByPlatformIdQueryKey = (platform?: string,
    platformId?: string,) => {
    return [
    `https://7tv.io/v3/users/${platform}/${platformId}`
    ] as const;
    }

    
export const getGetUserByPlatformIdQueryOptions = <TData = Awaited<ReturnType<typeof getUserByPlatformId>>, TError = ApiError>(platform: string,
    platformId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserByPlatformId>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserByPlatformIdQueryKey(platform,platformId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserByPlatformId>>> = ({ signal }) => getUserByPlatformId(platform,platformId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(platform && platformId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserByPlatformId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserByPlatformIdQueryResult = NonNullable<Awaited<ReturnType<typeof getUserByPlatformId>>>
export type GetUserByPlatformIdQueryError = ApiError


export function useGetUserByPlatformId<TData = Awaited<ReturnType<typeof getUserByPlatformId>>, TError = ApiError>(
 platform: string,
    platformId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserByPlatformId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserByPlatformId>>,
          TError,
          Awaited<ReturnType<typeof getUserByPlatformId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserByPlatformId<TData = Awaited<ReturnType<typeof getUserByPlatformId>>, TError = ApiError>(
 platform: string,
    platformId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserByPlatformId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserByPlatformId>>,
          TError,
          Awaited<ReturnType<typeof getUserByPlatformId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserByPlatformId<TData = Awaited<ReturnType<typeof getUserByPlatformId>>, TError = ApiError>(
 platform: string,
    platformId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserByPlatformId>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserByPlatformId<TData = Awaited<ReturnType<typeof getUserByPlatformId>>, TError = ApiError>(
 platform: string,
    platformId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserByPlatformId>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserByPlatformIdQueryOptions(platform,platformId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




